---
- name: MariaDB Installation
  hosts: all
  become: true
  tasks:
  - name: installing python-apt dependency
    apt: name={{item}} state=present
    with_items:
        - python-apt
        - python-pymysql

  - name: Install MariaDB repository
    apt_repository: repo='deb http://mirrors.nav.ro/mariadb//mariadb-10.4.12/repo/ubuntu/ trusty main' state=present
  - name: Add repository key to the system
    apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  - name: Install MariaDB Server
    apt: name=mariadb-server state=latest update_cache=yes
  - name: Start MariaDB
    service: name=mysql state=started
  - name: install mysql connector
    command: pip install mysql-connector-python
  - name: Create myapp database
    mysql_db:
        name: bobdata
        state: present
        login_host: localhost
        state: present
