---
- name: MariaDB Installation
  hosts: all
  become: true
  vars:
     mysql_root_password: "Password1"
  tasks:
  - name: Install MariaDB repository
    apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.4/ubuntu trusty main' state=present

  - name: Add repository key to the system
    apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

  - name: Install MariaDB Server
    apt: name=mariadb-server state=latest update_cache=yes

  - name: Start MariaDB
    service: name=mysql state=started

  - name: Create myapp database
    mysql_db:
        name: myapp
        login_user: root
        login_password: password
        login_host: localhost
        state: present
